/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LANDING_page.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/LANDING_page.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="31db453cac60470184ea88d396b93463fbx003" position={[0.02, -0.064, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.009} />
        <group name="Sketchfab_model010" position={[0, 0, 12.196]} rotation={[-Math.PI / 2, 0, 0]} scale={30.269}>
          <group name="31db453cac60470184ea88d396b93463fbx009" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode010" position={[0, 0, 6.59]}>
              <group name="default6002" position={[-0.183, 0, 6.421]} rotation={[0, 0.003, 0]}>
                <mesh name="default6_Material_0002" geometry={nodes.default6_Material_0002.geometry} material={materials['Material.018']} position={[12.568, -0.112, -21.427]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Wind" position={[-8.508, 3.356, -5.241]} rotation={[0, 0, 0.732]} />
        <group name="Turbulence" position={[-9.05, 2.334, -0.636]} />
        <mesh name="CafeBuilding_Texture_buildings1_0" geometry={nodes.CafeBuilding_Texture_buildings1_0.geometry} material={materials.Texture_buildings1} position={[-0.38, 0, 5.068]} rotation={[0, 1.55, 0]} />
        <mesh name="PizzaBuilding_Texture_buildings1_0" geometry={nodes.PizzaBuilding_Texture_buildings1_0.geometry} material={materials.Texture_buildings1} position={[-5.101, 0, 0.178]} rotation={[0, 0.011, 0]} />
        <mesh name="PizzaLight_Texture_buildings1_0" geometry={nodes.PizzaLight_Texture_buildings1_0.geometry} material={materials.Texture_buildings1} position={[0, 0, 3.105]} rotation={[-Math.PI, 0.08, -Math.PI]} />
        <mesh name="RestaurantBuilding_Texture_buildings1_0" geometry={nodes.RestaurantBuilding_Texture_buildings1_0.geometry} material={materials.Texture_buildings1} position={[5.173, 0, -0.202]} rotation={[-Math.PI, 0.023, -Math.PI]} />
        <mesh name="ShopBuilding_Texture_buildings1_0" geometry={nodes.ShopBuilding_Texture_buildings1_0.geometry} material={materials.Texture_buildings1} position={[-0.083, 0, -5.457]} rotation={[Math.PI, -1.558, Math.PI]} scale={1.125} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.046']} position={[-3.407, 0.206, 5.285]} rotation={[-1.293, 0.348, 1.485]} scale={0.418} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.048']} position={[-4.521, 0.187, 5.059]} rotation={[-1.293, 0.348, 1.485]} scale={[0.408, 0.356, 0.258]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.047']} position={[-4.96, 0.31, 4.187]} rotation={[1.707, 0.716, -0.071]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-2.579, 0.31, -5.306]} rotation={[-1.335, -0.377, -0.382]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-3.629, 0.187, -4.887]} rotation={[-1.335, -0.377, -0.382]} scale={[0.755, 0.658, 0.477]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-4.881, 0.333, -4.035]} rotation={[-1.335, -0.377, -0.382]} scale={0.487} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.049']} position={[-5.166, 0.29, -2.77]} rotation={[-1.487, 0.434, 1.985]} scale={0.418} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Grass} position={[0.019, -0.053, -0.022]} scale={[9.399, 0.939, 10.771]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.050']} position={[-4.881, 0.333, -4.035]} rotation={[-1.335, -0.377, -0.382]} scale={0.487} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.051']} position={[-3.629, 0.187, -4.887]} rotation={[-1.335, -0.377, -0.382]} scale={[0.755, 0.658, 0.477]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.052']} position={[-2.579, 0.31, -5.306]} rotation={[-1.335, -0.377, -0.382]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.041']} position={[4.333, 0.311, -5.037]} rotation={[-1.397, -0.409, -0.545]} scale={0.418} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.042']} position={[2.396, 0.051, -5.575]} rotation={[-1.202, 0.25, 1.181]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.043']} position={[3.276, 0.285, -5.183]} rotation={[-1.202, 0.25, 1.181]} scale={[-0.641, -0.414, -0.393]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.045']} position={[4.333, 0.287, 4.466]} rotation={[0.997, -1.157, 2.349]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.044']} position={[4.956, 0.311, 3.69]} rotation={[-1.817, 0.371, 2.788]} scale={0.418} />
        <mesh name="default7_Material_0010" geometry={nodes.default7_Material_0010.geometry} material={materials['Material.021']} position={[6.957, 0.02, -8.955]} scale={0.31} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.054']} position={[2.396, 0.051, -5.575]} rotation={[-1.202, 0.25, 1.181]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.055']} position={[2.396, 0.051, -5.575]} rotation={[-1.202, 0.25, 1.181]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.056']} position={[2.396, 0.051, -5.575]} rotation={[-1.202, 0.25, 1.181]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.057']} position={[3.276, 0.285, -5.183]} rotation={[-1.202, 0.25, 1.181]} scale={[-0.641, -0.414, -0.393]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.058']} position={[4.333, 0.311, -5.037]} rotation={[-1.397, -0.409, -0.545]} scale={0.418} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.059']} position={[3.276, 0.285, -5.183]} rotation={[-1.202, 0.25, 1.181]} scale={[-0.641, -0.414, -0.393]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.060']} position={[2.396, 0.051, -5.575]} rotation={[-1.202, 0.25, 1.181]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.061']} position={[4.333, 0.311, -5.037]} rotation={[-1.397, -0.409, -0.545]} scale={0.418} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.059']} position={[5.052, 0.285, -3.416]} rotation={[-1.883, 0.318, 2.984]} scale={[-0.641, -0.414, -0.393]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.060']} position={[4.788, 0.051, -2.452]} rotation={[-1.883, 0.318, 2.984]} scale={[0.407, 0.351, 0.257]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Material.061']} position={[5.046, 0.311, -4.541]} rotation={[-1.18, 0.212, 1.083]} scale={0.418} />
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={materials['Material.062']} position={[4.333, 0.287, 4.466]} rotation={[0.997, -1.157, 2.349]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials['Material.063']} position={[4.333, 0.287, 4.466]} rotation={[0.997, -1.157, 2.349]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials['Material.063']} position={[3.403, 0.238, 5.148]} rotation={[2.413, -0.27, -2.036]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Cube029" geometry={nodes.Cube029.geometry} material={materials['Material.047']} position={[-5.33, 0.181, 3.092]} rotation={[-1.506, 0.015, 0.59]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.065']} position={[-0.28, -0.002, 0.474]} scale={5.175} />
        <mesh name="Cube030" geometry={nodes.Cube030.geometry} material={materials['Material.063']} position={[3.087, 0.238, 6.079]} rotation={[-2.455, -0.637, -0.542]} scale={[0.586, 0.378, 0.36]} />
        <mesh name="default7_Material_0001" geometry={nodes.default7_Material_0001.geometry} material={materials['Material.066']} position={[6.957, 0.02, -8.955]} scale={0.31} />
        <mesh name="default7_Material_0002" geometry={nodes.default7_Material_0002.geometry} material={materials['Material.066']} position={[4.743, -0.058, -10.245]} scale={0.31} />
        <mesh name="default7_Material_0003" geometry={nodes.default7_Material_0003.geometry} material={materials['Material.066']} position={[2.642, -0.079, -10.466]} scale={0.31} />
        <mesh name="default7_Material_0004" geometry={nodes.default7_Material_0004.geometry} material={materials['Material.066']} position={[-0.98, -0.079, -10.466]} scale={0.31} />
        <mesh name="default7_Material_0005" geometry={nodes.default7_Material_0005.geometry} material={materials['Material.066']} position={[-0.98, -0.079, -8.286]} scale={0.31} />
        <mesh name="default7_Material_0006" geometry={nodes.default7_Material_0006.geometry} material={materials['Material.066']} position={[-6.305, -0.079, -8.286]} scale={0.31} />
        <mesh name="default7_Material_0007" geometry={nodes.default7_Material_0007.geometry} material={materials['Material.066']} position={[-6.305, -0.079, -3.891]} scale={0.31} />
        <mesh name="default7_Material_0008" geometry={nodes.default7_Material_0008.geometry} material={materials['Material.066']} position={[-8.188, -0.079, -3.891]} scale={0.31} />
        <mesh name="default7_Material_0009" geometry={nodes.default7_Material_0009.geometry} material={materials['Material.066']} position={[-8.188, -0.079, 4.801]} scale={0.31} />
        <mesh name="default7_Material_0011" geometry={nodes.default7_Material_0011.geometry} material={materials['Material.066']} position={[-8.188, -0.079, 7.35]} scale={0.31} />
        <mesh name="default7_Material_0012" geometry={nodes.default7_Material_0012.geometry} material={materials['Material.066']} position={[-8.188, -0.079, 7.35]} scale={0.31} />
        <mesh name="default7_Material_0013" geometry={nodes.default7_Material_0013.geometry} material={materials['Material.066']} position={[-5.303, -0.079, 7.35]} scale={0.31} />
        <mesh name="default7_Material_0014" geometry={nodes.default7_Material_0014.geometry} material={materials['Material.066']} position={[-5.303, -0.079, 10.309]} scale={0.31} />
        <mesh name="default7_Material_0015" geometry={nodes.default7_Material_0015.geometry} material={materials['Material.066']} position={[-1.62, -0.079, 10.309]} scale={0.31} />
        <mesh name="default7_Material_0016" geometry={nodes.default7_Material_0016.geometry} material={materials['Material.066']} position={[1.01, -0.079, 10.309]} scale={0.31} />
        <mesh name="default7_Material_0017" geometry={nodes.default7_Material_0017.geometry} material={materials['Material.066']} position={[1.01, -0.079, 8.342]} scale={0.31} />
        <mesh name="default7_Material_0018" geometry={nodes.default7_Material_0018.geometry} material={materials['Material.066']} position={[5.501, -0.079, 8.342]} scale={0.31} />
        <mesh name="default7_Material_0019" geometry={nodes.default7_Material_0019.geometry} material={materials['Material.066']} position={[7.553, -0.079, 8.342]} scale={0.31} />
        <mesh name="default7_Material_0020" geometry={nodes.default7_Material_0020.geometry} material={materials['Material.066']} position={[7.553, -0.079, 4.347]} scale={0.31} />
        <mesh name="default7_Material_0021" geometry={nodes.default7_Material_0021.geometry} material={materials['Material.066']} position={[7.553, -0.079, 2.703]} scale={0.31} />
        <mesh name="default7_Material_0022" geometry={nodes.default7_Material_0022.geometry} material={materials['Material.066']} position={[7.553, -0.079, -1.265]} scale={0.31} />
        <mesh name="default7_Material_0023" geometry={nodes.default7_Material_0023.geometry} material={materials['Material.066']} position={[7.553, -0.079, -5.368]} scale={0.31} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/LANDING_page.glb')
